from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

PATH_PATTERN = re.compile(r"`([^`\n]+\.(?:py|ts|tsx|json|sh|inc|md))`")

CROSS_REPO_PREFIXES = ("docs/", "../docs/", "../../docs/")

EXCLUDED_FILE_PREFIXES = ("frontend/",)

EXCLUDED_FILES = {
    "REFACTOR_PLAN.md",
}

EXPLICIT_EXCLUSIONS: dict[tuple[str, str], str] = {
    (
        "README.md",
        "public/data/demo-script.json",
    ): "a path inside frontend/public/, generated by a separate command; absent from git and from the image (README section 9)",
    **{
        (document, artifact): (
            "an artifact of a surrogate or OPM run: produced by a run on the author's machine, "
            "not stored in git (weights and exports live outside the repository)"
        )
        for document, artifact in (
            ("RELEASE_SURROGATE_20260906.md", "out/opm-release-tests.json"),
            ("RELEASE_SURROGATE_20260906.md", "out/metrics-full-pipeline.json"),
            ("RELEASE_SURROGATE_20260906.md", "out/production-ood-check.json"),
            ("RELEASE_SURROGATE_20260906.md", "out/surrogate-runtime.json"),
            ("SURROGATE_DEFENSE.md", "data/npv-v6/direct-refit-locked/lock_report.json"),
            ("UNSEEN_CASE_2017.md", "prediction/response.json"),
        )
    },
}

def _is_excluded_path(path: str) -> bool:
    if "/" not in path:
        return True
    if path.startswith(CROSS_REPO_PREFIXES):
        return True
    if "<" in path or "*" in path:
        return True
    if path.startswith("/") or path.startswith("w:"):
        return True
    return False

def tracked_markdown_files(root: Path) -> list[Path]:
    output = subprocess.run(
        ["git", "ls-files", "*.md"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return [root / line for line in output.splitlines() if line]

def find_broken_links(root: Path, md_files: list[Path]) -> list[tuple[str, int, str]]:
    broken: list[tuple[str, int, str]] = []
    for md_file in md_files:
        relative = str(md_file.relative_to(root))
        if relative.startswith(EXCLUDED_FILE_PREFIXES) or relative in EXCLUDED_FILES:
            continue
        for lineno, line in enumerate(md_file.read_text(encoding="utf-8").splitlines(), 1):
            for match in PATH_PATTERN.finditer(line):
                candidate = match.group(1)
                if _is_excluded_path(candidate):
                    continue
                if (relative, candidate) in EXPLICIT_EXCLUSIONS:
                    continue
                resolved_from_root = (root / candidate).exists()
                resolved_from_file_dir = (md_file.parent / candidate).exists()
                if not resolved_from_root and not resolved_from_file_dir:
                    broken.append((relative, lineno, candidate))
    return broken

def test_no_broken_markdown_links() -> None:
    md_files = tracked_markdown_files(REPO_ROOT)
    assert md_files, "no tracked .md file was found"
    broken = find_broken_links(REPO_ROOT, md_files)
    assert not broken, "dead links to files:\n" + "\n".join(
        f"{file}:{line}: `{path}`" for file, line, path in broken
    )

def test_broken_link_is_detected(tmp_path: Path) -> None:
    (tmp_path / "existing.py").write_text("", encoding="utf-8")
    doc = tmp_path / "NOTE.md"
    doc.write_text(
        "a working link `existing.py`\n"
        "a broken link `pkg/missing_module.py` on the second line\n",
        encoding="utf-8",
    )

    broken = find_broken_links(tmp_path, [doc])

    assert broken == [("NOTE.md", 2, "pkg/missing_module.py")]
