from __future__ import annotations

REMOVED_IN_WAVE = 3
REMOVAL_DATE = "2026-09-13"

EXTERNAL_ENTRYPOINTS: frozenset[str] = frozenset(
    {
        "backend.presentation.cli.emit",
        "backend.presentation.cli.final_campaign",
        "backend.presentation.cli.jarvis",
        "backend.presentation.cli.npv",
        "backend.presentation.cli.run",
        "backend.presentation.cli.selfcheck",
        "backend.presentation.cli.surrogate_check",
        "backend.presentation.cli.verify_reference",
        "backend.presentation.cli.web",
        "backend.presentation.cli.web_run_worker",
        "backend.presentation.ui_export.demo",
    }
)

MODULE_SHIMS: dict[str, str] = {
    "backend.core.contracts.hashing": "backend.shared.hashing",
    "backend.application.cases": "backend.contexts.constraints.application.cases",
    "backend.application.connectivity_campaign": "backend.contexts.connectivity.application.connectivity_campaign",
    "backend.application.connectivity_measure": "backend.contexts.connectivity.application.connectivity_measure",
    "backend.application.connectivity_plan": "backend.contexts.connectivity.application.connectivity_plan",
    "backend.application.jarvis.answer": "backend.contexts.assistant.application.answer",
    "backend.application.jarvis.artifacts": "backend.contexts.assistant.infrastructure.artifacts",
    "backend.application.jarvis.caption": "backend.contexts.assistant.application.caption",
    "backend.application.jarvis.docs_index": "backend.contexts.assistant.infrastructure.docs_index",
    "backend.application.jarvis.fixtures": "backend.contexts.assistant.application.recording_replay",
    "backend.application.jarvis.guard": "backend.contexts.assistant.domain.guard",
    "backend.application.jarvis.knowledge": "backend.contexts.assistant.infrastructure.knowledge",
    "backend.application.jarvis.orchestrator": "backend.contexts.assistant.application.orchestrator",
    "backend.application.jarvis.prompt": "backend.contexts.assistant.infrastructure.prompt",
    "backend.application.jarvis.recordings": "backend.contexts.assistant.infrastructure.recordings",
    "backend.application.jarvis.session": "backend.contexts.assistant.domain.session",
    "backend.application.jarvis.session_store": "backend.contexts.assistant.infrastructure.session_store",
    "backend.application.jarvis.stt": "backend.contexts.assistant.infrastructure.stt",
    "backend.application.jarvis.suggestions": "backend.contexts.assistant.application.suggestions",
    "backend.application.jarvis.system_map": "backend.contexts.assistant.infrastructure.system_map",
    "backend.application.jarvis.tools": "backend.contexts.assistant.application.tools",
    "backend.application.jarvis.tts": "backend.contexts.assistant.infrastructure.tts",
    "backend.application.optimization.champion": "backend.contexts.optimization.infrastructure.champion",
    "backend.application.optimization.convergence": "backend.contexts.optimization.domain.convergence",
    "backend.application.optimization.interface": "backend.contexts.optimization.domain.interface",
    "backend.application.optimization.linalg": "backend.contexts.optimization.domain.linalg",
    "backend.application.optimization.observed_repair": "backend.contexts.optimization.domain.observed_repair",
    "backend.application.optimization.opm_active_calibration": "backend.contexts.optimization.application.opm_active_calibration",
    "backend.application.optimization.runtime_artifacts": "backend.contexts.optimization.infrastructure.artifacts",
    "backend.application.optimization.scenario_baseline": "backend.contexts.optimization.application.scenario_baseline",
    "backend.application.optimization.schedule_search": "backend.contexts.optimization.application.environment",
    "backend.application.optimization.search": "backend.contexts.optimization.domain.optimizer",
    "backend.application.optimization.search_run": "backend.contexts.optimization.application.search_use_case",
    "backend.application.optimization.verification": "backend.contexts.optimization.application.verification",
    "backend.application.optimization.verification_run": "backend.contexts.optimization.application.verification_run",
    "backend.application.optimization.water_baseline_run": "backend.contexts.optimization.application.water_baseline_run",
    "backend.application.runs.workflow": "backend.contexts.runs.application.workflow",
    "backend.core.contracts.config": "backend.contexts.constraints.domain.config",
    "backend.core.contracts.connectivity": "backend.contexts.connectivity.domain.connectivity",
    "backend.core.contracts.constraints": "backend.contexts.constraints.domain.constraints",
    "backend.core.contracts.economics": "backend.contexts.economics.domain.economics",
    "backend.core.contracts.policy": "backend.contexts.policy.domain.policy",
    "backend.core.contracts.response": "backend.contexts.reservoir.domain.response",
    "backend.core.contracts.run_artifact": "backend.contexts.runs.domain.run_artifact",
    "backend.core.contracts.schedule": "backend.contexts.schedule.domain.schedule",
    "backend.core.contracts.simulation": "backend.contexts.runs.domain.run_result",
    "backend.core.horizon": "backend.contexts.reservoir.domain.horizon",
    "backend.core.provenance": "backend.contexts.runs.infrastructure.provenance",
    "backend.domain.configuration.constraints_io": "backend.contexts.constraints.infrastructure.constraints_io",
    "backend.domain.configuration.io": "backend.contexts.constraints.infrastructure.io",
    "backend.domain.configuration.normatives": "backend.contexts.constraints.domain.normatives",
    "backend.domain.configuration.schema": "backend.contexts.constraints.domain.schema",
    "backend.domain.connectivity.amplitude": "backend.contexts.connectivity.domain.amplitude",
    "backend.domain.connectivity.campaign": "backend.contexts.connectivity.application.campaign",
    "backend.domain.connectivity.deck": "backend.contexts.connectivity.infrastructure.deck",
    "backend.domain.connectivity.doe": "backend.contexts.connectivity.domain.doe",
    "backend.domain.connectivity.estimator": "backend.contexts.connectivity.domain.estimator",
    "backend.domain.connectivity.fund": "backend.contexts.connectivity.domain.fund",
    "backend.domain.connectivity.groups": "backend.contexts.connectivity.domain.groups",
    "backend.domain.connectivity.groups_artifact": "backend.contexts.connectivity.infrastructure.groups_artifact",
    "backend.domain.connectivity.hadamard": "backend.contexts.connectivity.domain.hadamard",
    "backend.domain.connectivity.measure": "backend.contexts.connectivity.domain.measure",
    "backend.domain.connectivity.setpoints": "backend.contexts.connectivity.domain.setpoints",
    "backend.domain.connectivity.sweep": "backend.contexts.connectivity.domain.sweep",
    "backend.domain.economics.base_case": "backend.contexts.economics.application.base_case",
    "backend.domain.economics.decomposition": "backend.contexts.economics.domain.decomposition",
    "backend.domain.economics.esp": "backend.contexts.economics.domain.esp",
    "backend.domain.economics.fund": "backend.contexts.economics.domain.fund",
    "backend.domain.economics.ledger": "backend.contexts.economics.domain.ledger",
    "backend.domain.economics.methodology_hash": "backend.contexts.economics.domain.methodology_hash",
    "backend.domain.economics.normatives_io": "backend.contexts.economics.infrastructure.normatives_io",
    "backend.domain.economics.npv": "backend.contexts.economics.domain.npv",
    "backend.domain.economics.reference_parity": "backend.contexts.economics.application.reference_parity",
    "backend.domain.policy.agents": "backend.contexts.policy.domain.agents",
    "backend.domain.policy.budget": "backend.contexts.policy.domain.budget",
    "backend.domain.policy.economics": "backend.contexts.policy.domain.economics",
    "backend.domain.policy.fixed_point": "backend.contexts.policy.domain.fixed_point",
    "backend.domain.policy.flags": "backend.contexts.policy.domain.flags",
    "backend.domain.policy.hierarchy": "backend.contexts.policy.application.hierarchy",
    "backend.domain.policy.levels": "backend.contexts.policy.domain.levels",
    "backend.domain.policy.memory": "backend.contexts.policy.domain.memory",
    "backend.domain.policy.rules": "backend.contexts.policy.domain.rules",
    "backend.domain.policy.state": "backend.contexts.policy.domain.state",
    "backend.domain.policy.theta": "backend.contexts.policy.domain.theta",
    "backend.domain.policy.trace": "backend.contexts.policy.domain.trace",
    "backend.domain.robustness.battery": "backend.contexts.robustness.application.battery",
    "backend.domain.robustness.catalog": "backend.contexts.robustness.domain.catalog",
    "backend.domain.robustness.perturbation": "backend.contexts.robustness.domain.perturbation",
    "backend.domain.robustness.regret": "backend.contexts.robustness.domain.regret",
    "backend.domain.schedule.build": "backend.contexts.schedule.domain.build",
    "backend.domain.schedule.canonical": "backend.contexts.schedule.domain.canonical",
    "backend.domain.schedule.case_limits": "backend.contexts.schedule.domain.case_limits",
    "backend.domain.schedule.emit": "backend.contexts.schedule.application.emit",
    "backend.domain.schedule.json_io": "backend.contexts.schedule.infrastructure.json_io",
    "backend.domain.schedule.lossless": "backend.contexts.schedule.domain.lossless",
    "backend.domain.schedule.replay": "backend.contexts.schedule.domain.replay",
    "backend.domain.schedule.validate": "backend.contexts.schedule.domain.validate",
    "backend.domain.schedule.validate_dynamic": "backend.contexts.schedule.domain.validate_dynamic",
    "backend.domain.schedule.wcon": "backend.contexts.schedule.domain.wcon",
    "backend.infrastructure.llm": "backend.contexts.assistant.infrastructure.llm",
    "backend.infrastructure.opm.base_run": "backend.contexts.simulation.application.baseline_diagnostics",
    "backend.infrastructure.opm.cache": "backend.contexts.simulation.infrastructure.cache",
    "backend.infrastructure.opm.dataset": "backend.contexts.simulation.infrastructure.dataset",
    "backend.infrastructure.opm.dataset_plan": "backend.contexts.simulation.domain.perturbation_design",
    "backend.infrastructure.opm.opm_deck": "backend.contexts.reservoir.infrastructure.opm_deck",
    "backend.infrastructure.opm.preflight": "backend.contexts.simulation.infrastructure.preflight",
    "backend.infrastructure.opm.pvt": "backend.contexts.reservoir.infrastructure.pvt",
    "backend.infrastructure.opm.response_loader": "backend.contexts.simulation.infrastructure.response_loader",
    "backend.infrastructure.opm.runner": "backend.contexts.simulation.infrastructure.runner",
    "backend.infrastructure.opm.submission": "backend.contexts.simulation.application.submission",
    "backend.infrastructure.opm.summary": "backend.contexts.reservoir.infrastructure.summary",
    "backend.infrastructure.resources": "backend.shared.resources",
    "backend.ml.surrogate.adapter": "backend.contexts.surrogate.application.adapter",
    "backend.ml.surrogate.crm": "backend.contexts.surrogate.domain.crm",
    "backend.ml.surrogate.cycle": "backend.contexts.surrogate.application.pipeline",
    "backend.ml.surrogate.dashboard": "backend.interfaces.http.surrogate_dashboard.server",
    "backend.ml.surrogate.ensemble": "backend.contexts.surrogate.application.ensemble",
    "backend.ml.surrogate.features": "backend.contexts.surrogate.domain.features",
    "backend.ml.surrogate.metrics": "backend.contexts.surrogate.domain.metrics",
    "backend.ml.surrogate.model": "backend.contexts.surrogate.application.model",
    "backend.ml.surrogate.model_z_context": "backend.contexts.surrogate.infrastructure.model_z_context",
    "backend.ml.surrogate.npv_block_head": "backend.contexts.surrogate.domain.npv_block_head",
    "backend.ml.surrogate.npv_calibration": "backend.contexts.surrogate.domain.npv_calibration",
    "backend.ml.surrogate.npv_economic_features": "backend.contexts.surrogate.domain.npv_economic_features",
    "backend.ml.surrogate.npv_head": "backend.contexts.surrogate.domain.npv_head",
    "backend.ml.surrogate.npv_target": "backend.contexts.surrogate.domain.npv_target",
    "backend.ml.surrogate.ood": "backend.contexts.robustness.domain.ood",
    "backend.ml.surrogate.physics_checks": "backend.contexts.surrogate.domain.physics_checks",
    "backend.ml.surrogate.raw_model_output": "backend.contexts.surrogate.domain.raw_model_output",
    "backend.ml.surrogate.scenario_ood": "backend.contexts.robustness.domain.scenario_ood",
    "backend.ml.surrogate.schedule_roles": "backend.contexts.surrogate.domain.schedule_roles",
    "backend.ml.surrogate.train": "backend.contexts.surrogate.application.train",
    "backend.presentation.api.jarvis_server": "backend.interfaces.http.assistant.server",
    "backend.presentation.api.proxy": "backend.interfaces.http.console.proxy",
    "backend.presentation.api.service": "backend.contexts.assistant.application.assistant_service",
    "backend.presentation.api.sse": "backend.interfaces.http.kit.sse",
    "backend.presentation.cli.emit": "backend.interfaces.cli.emit",
    "backend.presentation.cli.final_campaign": "backend.interfaces.cli.final_campaign",
    "backend.presentation.cli.jarvis": "backend.interfaces.cli.jarvis",
    "backend.presentation.cli.loader": "backend.interfaces.cli.loader",
    "backend.presentation.cli.npv": "backend.interfaces.cli.npv",
    "backend.presentation.cli.paths": "backend.interfaces.cli.paths",
    "backend.presentation.cli.run": "backend.interfaces.cli.run",
    "backend.presentation.cli.selfcheck": "backend.interfaces.cli.selfcheck",
    "backend.presentation.cli.surrogate_adapt": "backend.interfaces.cli.surrogate.adapt",
    "backend.presentation.cli.surrogate_adapt_audit": "backend.interfaces.cli.surrogate.adapt_audit",
    "backend.presentation.cli.surrogate_audit": "backend.interfaces.cli.surrogate.audit",
    "backend.presentation.cli.surrogate_check": "backend.interfaces.cli.surrogate.check",
    "backend.presentation.cli.surrogate_release": "backend.interfaces.cli.surrogate.release",
    "backend.presentation.cli.surrogate_screen": "backend.interfaces.cli.surrogate.screen",
    "backend.presentation.cli.surrogate_screen_verify": "backend.interfaces.cli.surrogate.screen_verify",
    "backend.presentation.cli.surrogate_tools": "backend.interfaces.cli.surrogate.tools",
    "backend.presentation.cli.surrogate_weight_soup": "backend.interfaces.cli.surrogate.weight_soup",
    "backend.presentation.cli.verify_reference": "backend.interfaces.cli.verify_reference",
    "backend.presentation.cli.web": "backend.interfaces.cli.web",
    "backend.presentation.cli.web_run_worker": "backend.interfaces.cli.web_run_worker",
    "backend.presentation.cli.web_runs": "backend.contexts.runs.application.web_runs",
    "backend.presentation.ui_export.ablation_view": "backend.contexts.showcase.application.exporters.ablation_view",
    "backend.presentation.ui_export.artifact_io": "backend.contexts.showcase.infrastructure.artifact_io",
    "backend.presentation.ui_export.base_artifact": "backend.contexts.showcase.application.base_artifact",
    "backend.presentation.ui_export.champion_export": "backend.contexts.showcase.application.champion_export",
    "backend.presentation.ui_export.compensation_view": "backend.contexts.showcase.application.exporters.compensation_view",
    "backend.presentation.ui_export.deck": "backend.contexts.reservoir.application.deck",
    "backend.presentation.ui_export.demo": "backend.contexts.showcase.application.build_showcase",
    "backend.presentation.ui_export.demo_artifact": "backend.contexts.showcase.infrastructure.synthetic_artifact",
    "backend.presentation.ui_export.demo_response": "backend.contexts.showcase.infrastructure.synthetic_response",
    "backend.presentation.ui_export.demo_rng": "backend.contexts.showcase.infrastructure.synthetic_rng",
    "backend.presentation.ui_export.graph_view": "backend.contexts.showcase.application.exporters.graph_view",
    "backend.presentation.ui_export.hierarchy_view": "backend.contexts.showcase.application.exporters.hierarchy_view",
    "backend.presentation.ui_export.maps_view": "backend.contexts.showcase.application.exporters.maps_view",
    "backend.presentation.ui_export.npv_view": "backend.contexts.showcase.application.exporters.npv_view",
    "backend.presentation.ui_export.physics_view": "backend.contexts.showcase.application.exporters.physics_view",
    "backend.presentation.ui_export.plan_export": "backend.contexts.showcase.application.plan_export",
    "backend.presentation.ui_export.run_summary": "backend.contexts.showcase.application.run_summary",
    "backend.presentation.ui_export.scenarios": "backend.contexts.showcase.application.scenarios",
    "backend.presentation.ui_export.timeline": "backend.contexts.showcase.application.exporters.timeline",
    "backend.presentation.ui_export.webdata": "backend.contexts.reservoir.application.well_geometry",
}

PACKAGE_SHIMS: tuple[str, ...] = (
    "backend.core.contracts",
    "backend.domain.schedule",
    "backend.domain.economics",
    "backend.domain.configuration",
    "backend.domain.connectivity",
    "backend.domain.policy",
    "backend.domain.robustness",
    "backend.ml.surrogate",
    "backend.application.optimization",
    "backend.application.runs",
    "backend.application.jarvis",
    "backend.infrastructure.opm",
    "backend.presentation.cli",
)

__all__ = [
    "EXTERNAL_ENTRYPOINTS",
    "MODULE_SHIMS",
    "PACKAGE_SHIMS",
    "REMOVAL_DATE",
    "REMOVED_IN_WAVE",
]
