from __future__ import annotations

from backend.contexts.assistant.domain.errors import DocsIndexError
from backend.contexts.assistant.infrastructure.docs_index.chunking import (
    chunks_of_knowledge,
    chunks_of_markdown,
    chunks_of_plain,
)
from backend.contexts.assistant.infrastructure.docs_index.index import (
    BM25_B,
    BM25_K1,
    CACHE_VERSION,
    DEFAULT_K,
    HEADING_WEIGHT,
    MAX_K,
    PLANNING_PENALTY,
    PLANNING_SOURCES,
    SCOPES,
    DocsIndex,
)
from backend.contexts.assistant.infrastructure.docs_index.models import Chunk, Hit, Stamp
from backend.contexts.assistant.infrastructure.docs_index.sources import (
    CACHE_NAME,
    DOCS_ENV_VAR,
    OUT_ENV_VAR,
    ROOT_MARKDOWN_LIMIT,
    default_cache_path,
    default_roots,
    repository_root,
)
from backend.contexts.assistant.infrastructure.docs_index.store import (
    PROCESS_DOCS_CACHE,
    DocsIndexCache,
    collect_chunks,
    load_index,
    reset_shared_index,
    shared_index,
)
from backend.contexts.assistant.infrastructure.docs_index.text import (
    CHUNK_LIMIT,
    CHUNK_OVERLAP,
    EN_SUFFIXES,
    FENCE_PATTERN,
    HEADING_PATTERN,
    MIN_STEM_LENGTH,
    NUMBER_PATTERN,
    RU_SUFFIXES,
    SLUG_DROP,
    SNIPPET_LIMIT,
    TOKEN_PATTERN,
    numbers_in,
    slug,
    stem,
    tokenize,
)

__all__ = [
    "BM25_B",
    "BM25_K1",
    "CACHE_NAME",
    "CACHE_VERSION",
    "CHUNK_LIMIT",
    "CHUNK_OVERLAP",
    "DEFAULT_K",
    "DOCS_ENV_VAR",
    "EN_SUFFIXES",
    "FENCE_PATTERN",
    "HEADING_PATTERN",
    "HEADING_WEIGHT",
    "MAX_K",
    "MIN_STEM_LENGTH",
    "NUMBER_PATTERN",
    "OUT_ENV_VAR",
    "PLANNING_PENALTY",
    "PLANNING_SOURCES",
    "PROCESS_DOCS_CACHE",
    "ROOT_MARKDOWN_LIMIT",
    "RU_SUFFIXES",
    "SCOPES",
    "SLUG_DROP",
    "SNIPPET_LIMIT",
    "TOKEN_PATTERN",
    "Chunk",
    "DocsIndex",
    "DocsIndexCache",
    "DocsIndexError",
    "Hit",
    "Stamp",
    "chunks_of_knowledge",
    "chunks_of_markdown",
    "chunks_of_plain",
    "collect_chunks",
    "default_cache_path",
    "default_roots",
    "load_index",
    "numbers_in",
    "repository_root",
    "reset_shared_index",
    "shared_index",
    "slug",
    "stem",
    "tokenize",
]
