from __future__ import annotations

from backend.core.contracts import (
    N_INTERVALS,
)
from backend.contexts.constraints.domain.constraints import (
    BHP_INJECTOR_MAX_BAR,
    BHP_PRODUCER_MIN_BAR,
    COMPENSATION_ENFORCEMENT,
    COMPENSATION_MAX,
    COMPENSATION_MIN,
    COMPENSATION_SCOPE,
    EXTERNAL_WATER_M3_PER_DAY,
    PRESSURE_CEILING_BAR,
    PRESSURE_FLOOR_BAR,
    REGION_PRESSURE_CEILING_BAR,
    REGION_PRESSURE_FLOOR_BAR,
    WATER_REINJECTION_FRACTION,
    WATER_REINJECTION_LAG_STEPS,
    WATER_SUPPLY_UNLIMITED,
)
from backend.contexts.reservoir.domain.response import N_DECK_DATES
from backend.contexts.schedule.domain.validate import (
    CONSTRAINT_WELL_OUTAGES_STATIC,
    CONSTRAINT_COMPENSATION,
    CONSTRAINT_COMPENSATION_SCOPE,
    CONSTRAINT_INJECTION_LIMITS,
    CONSTRAINT_LIQUID_LIMITS,
    CONSTRAINT_OIL_LIMITS,
    CONSTRAINT_PRODUCTION_FLOORS,
    CONSTRAINT_WATER_SUPPLY,
    CONSTRAINT_WATERCUT_LIMITS,
    CONSTRAINT_WELL_OUTAGES,
    CONSTRAINT_BHP_LIMITS,
    CONSTRAINT_FIELD_PRESSURE,
    CONSTRAINT_REGION_PRESSURE,
    CONSTRAINT_MATERIAL_BALANCE,
    ViolationKind,
)


COMPENSATION_FIELD_SCOPES: frozenset[str] = frozenset(
    {"field", "field_and_groups"}
)


COMPENSATION_GROUP_SCOPES: frozenset[str] = frozenset(
    {"groups", "field_and_groups"}
)


FIRST_CONTROL_DECK_DATE_INDEX: int = N_DECK_DATES - N_INTERVALS - 1


FIRST_CONTROL_LEVEL_DECK_DATE_INDEX: int = FIRST_CONTROL_DECK_DATE_INDEX + 1


DYNAMIC_CONSTRAINT_NAMES: tuple[str, ...] = (
    CONSTRAINT_LIQUID_LIMITS,
    CONSTRAINT_INJECTION_LIMITS,
    CONSTRAINT_PRODUCTION_FLOORS,
    CONSTRAINT_OIL_LIMITS,
    CONSTRAINT_WATERCUT_LIMITS,
    CONSTRAINT_WATER_SUPPLY,
    CONSTRAINT_WELL_OUTAGES,
    CONSTRAINT_COMPENSATION,
    CONSTRAINT_COMPENSATION_SCOPE,
    CONSTRAINT_FIELD_PRESSURE,
    CONSTRAINT_REGION_PRESSURE,
    CONSTRAINT_MATERIAL_BALANCE,
)


_CONSTRAINT_KINDS: dict[str, tuple[ViolationKind, ...]] = {
    CONSTRAINT_BHP_LIMITS: (
        ViolationKind.BHP_BELOW_PRODUCER_LIMIT,
        ViolationKind.BHP_ABOVE_INJECTOR_LIMIT,
    ),
    CONSTRAINT_LIQUID_LIMITS: (ViolationKind.LIQUID_LIMIT_EXCEEDED,),
    CONSTRAINT_INJECTION_LIMITS: (ViolationKind.INJECTION_LIMIT_EXCEEDED,),
    CONSTRAINT_PRODUCTION_FLOORS: (ViolationKind.PRODUCTION_FLOOR_MISSED,),
    CONSTRAINT_OIL_LIMITS: (ViolationKind.OIL_LIMIT_EXCEEDED,),
    CONSTRAINT_WATERCUT_LIMITS: (ViolationKind.WATERCUT_LIMIT_EXCEEDED,),
    CONSTRAINT_WATER_SUPPLY: (ViolationKind.WATER_SUPPLY_LIMIT_EXCEEDED,),
    CONSTRAINT_WELL_OUTAGES: (ViolationKind.OUTAGE_WELL_PRODUCED,),
    CONSTRAINT_COMPENSATION: (
        ViolationKind.COMPENSATION_OUT_OF_CORRIDOR,
        ViolationKind.COMPENSATION_UNDEFINED,
    ),
    CONSTRAINT_COMPENSATION_SCOPE: (
        ViolationKind.COMPENSATION_OUT_OF_CORRIDOR,
        ViolationKind.COMPENSATION_UNDEFINED,
    ),
    CONSTRAINT_FIELD_PRESSURE: (
        ViolationKind.FIELD_PRESSURE_BELOW_FLOOR,
        ViolationKind.FIELD_PRESSURE_ABOVE_CEILING,
    ),
    CONSTRAINT_REGION_PRESSURE: (
        ViolationKind.REGION_PRESSURE_BELOW_FLOOR,
        ViolationKind.REGION_PRESSURE_ABOVE_CEILING,
    ),
    CONSTRAINT_MATERIAL_BALANCE: (ViolationKind.MATERIAL_BALANCE_BROKEN,),
}


CONSTRAINT_FIELD_COVERAGE: dict[str, tuple[str, ...]] = {
    "liquid_limits": (CONSTRAINT_LIQUID_LIMITS,),
    "injection_limits": (CONSTRAINT_INJECTION_LIMITS,),
    "production_floors": (CONSTRAINT_PRODUCTION_FLOORS,),
    "oil_limits": (CONSTRAINT_OIL_LIMITS,),
    "watercut_limits": (CONSTRAINT_WATERCUT_LIMITS,),
    "well_outages": (CONSTRAINT_WELL_OUTAGES, CONSTRAINT_WELL_OUTAGES_STATIC),
    WATER_SUPPLY_UNLIMITED: (CONSTRAINT_WATER_SUPPLY,),
    WATER_REINJECTION_FRACTION: (CONSTRAINT_WATER_SUPPLY,),
    WATER_REINJECTION_LAG_STEPS: (CONSTRAINT_WATER_SUPPLY,),
    EXTERNAL_WATER_M3_PER_DAY: (CONSTRAINT_WATER_SUPPLY,),
    COMPENSATION_MIN: (CONSTRAINT_COMPENSATION,),
    COMPENSATION_MAX: (CONSTRAINT_COMPENSATION,),
    COMPENSATION_ENFORCEMENT: (CONSTRAINT_COMPENSATION,),
    COMPENSATION_SCOPE: (CONSTRAINT_COMPENSATION_SCOPE,),
    BHP_PRODUCER_MIN_BAR: (CONSTRAINT_BHP_LIMITS,),
    BHP_INJECTOR_MAX_BAR: (CONSTRAINT_BHP_LIMITS,),
    PRESSURE_FLOOR_BAR: (CONSTRAINT_FIELD_PRESSURE,),
    PRESSURE_CEILING_BAR: (CONSTRAINT_FIELD_PRESSURE,),
    REGION_PRESSURE_FLOOR_BAR: (CONSTRAINT_REGION_PRESSURE,),
    REGION_PRESSURE_CEILING_BAR: (CONSTRAINT_REGION_PRESSURE,),
}


PHYSICS_CONSTRAINT_NAMES: tuple[str, ...] = (CONSTRAINT_MATERIAL_BALANCE,)


PROVENANCE_FIELDS: frozenset[str] = frozenset({"infrastructure", "case_path"})


COMPENSATION_SURFACE_CONDITIONS: str = "поверхностные условия"


COMPENSATION_RESERVOIR_CONDITIONS: str = "пластовые условия"


COMPENSATION_SURFACE_NOTICE: str = (
    "объёмные коэффициенты B_o/B_w в валидатор не переданы: C(k) считается "
    "в поверхностных условиях, пересчёт в пластовые не выполнялся"
)


__all__ = [
    "COMPENSATION_FIELD_SCOPES",
    "COMPENSATION_GROUP_SCOPES",
    "COMPENSATION_RESERVOIR_CONDITIONS",
    "COMPENSATION_SURFACE_CONDITIONS",
    "COMPENSATION_SURFACE_NOTICE",
    "CONSTRAINT_FIELD_COVERAGE",
    "DYNAMIC_CONSTRAINT_NAMES",
    "FIRST_CONTROL_DECK_DATE_INDEX",
    "FIRST_CONTROL_LEVEL_DECK_DATE_INDEX",
    "PHYSICS_CONSTRAINT_NAMES",
    "PROVENANCE_FIELDS",
]
