from __future__ import annotations

from backend.contexts.economics.domain.decomposition import (
    DecompositionError,
    EXACT_PER_WELL_FIELDS,
    IntervalPoint,
    IntervalSeries,
    InvariantReport,
    InvariantResidual,
    MACHINE_RELATIVE_TOLERANCE,
    MACHINE_ZERO_RUB,
    NpvDecomposition,
    TAX_BASIS_CAPTION,
    TaxBasis,
    WellContribution,
    WellRanking,
    annual_income_tax_by_well,
    check_invariants,
    check_monthly_to_annual,
    check_per_well_to_total,
    decompose,
    interval_series,
    well_contributions_from_flows,
    well_ranking,
)


__all__ = [
    "DecompositionError",
    "EXACT_PER_WELL_FIELDS",
    "IntervalPoint",
    "IntervalSeries",
    "InvariantReport",
    "InvariantResidual",
    "MACHINE_RELATIVE_TOLERANCE",
    "MACHINE_ZERO_RUB",
    "NpvDecomposition",
    "TAX_BASIS_CAPTION",
    "TaxBasis",
    "WellContribution",
    "WellRanking",
    "annual_income_tax_by_well",
    "check_invariants",
    "check_monthly_to_annual",
    "check_per_well_to_total",
    "decompose",
    "interval_series",
    "well_contributions_from_flows",
    "well_ranking",
]
